.ALTER SS_VDD_MAX_TEMP_MAX
.lib "../../device_models/ptm130/ptm-130.lib" SS
.TEMP {T_MAX}
.PARAM vdd={VDD_MAX}

.ALTER SS_VDD_MAX_TEMP_MIN
.lib "../../device_models/ptm130/ptm-130.lib" SS
.TEMP {T_MIN}
.PARAM vdd={VDD_MAX}

.ALTER SS_VDD_MIN_TEMP_MAX
.lib "../../device_models/ptm130/ptm-130.lib" SS
.TEMP {T_MAX}
.PARAM vdd={VDD_MIN}

.ALTER SS_VDD_MIN_TEMP_MIN
.lib "../../device_models/ptm130/ptm-130.lib" SS
.TEMP {T_MIN}
.PARAM vdd={VDD_MIN}



.ALTER FF_VDD_MAX_TEMP_MAX
.lib "../../device_models/ptm130/ptm-130.lib" FF
.TEMP {T_MAX}
.PARAM vdd={VDD_MAX}

.ALTER FF_VDD_MAX_TEMP_MIN
.lib "../../device_models/ptm130/ptm-130.lib" FF
.TEMP {T_MIN}
.PARAM vdd={VDD_MAX}

.ALTER FF_VDD_MIN_TEMP_MAX
.lib "../../device_models/ptm130/ptm-130.lib" FF
.TEMP {T_MAX}
.PARAM vdd={VDD_MIN}

.ALTER FF_VDD_MIN_TEMP_MIN
.lib "../../device_models/ptm130/ptm-130.lib" FF
.TEMP {T_MIN}
.PARAM vdd={VDD_MIN}


.ALTER SNFP_VDD_MAX_TEMP_MAX
.lib "../../device_models/ptm130/ptm-130.lib" SNFP
.TEMP {T_MAX}
.PARAM vdd={VDD_MAX}

.ALTER SNFP_VDD_MAX_TEMP_MIN
.lib "../../device_models/ptm130/ptm-130.lib" SNFP
.TEMP {T_MIN}
.PARAM vdd={VDD_MAX}

.ALTER SNFP_VDD_MIN_TEMP_MAX
.lib "../../device_models/ptm130/ptm-130.lib" SNFP
.TEMP {T_MAX}
.PARAM vdd={VDD_MIN}

.ALTER SNFP_VDD_MIN_TEMP_MIN
.lib "../../device_models/ptm130/ptm-130.lib" SNFP
.TEMP {T_MIN}
.PARAM vdd={VDD_MIN}



.ALTER FNSP_VDD_MAX_TEMP_MAX
.lib "../../device_models/ptm130/ptm-130.lib" FNSP
.TEMP {T_MAX}
.PARAM vdd={VDD_MAX}

.ALTER FNSP_VDD_MAX_TEMP_MIN
.lib "../../device_models/ptm130/ptm-130.lib" FNSP
.TEMP {T_MIN}
.PARAM vdd={VDD_MAX}

.ALTER FNSP_VDD_MIN_TEMP_MAX
.lib "../../device_models/ptm130/ptm-130.lib" FNSP
.TEMP {T_MAX}
.PARAM vdd={VDD_MIN}

.ALTER FNSP_VDD_MIN_TEMP_MIN
.lib "../../device_models/ptm130/ptm-130.lib" FNSP
.TEMP {T_MIN}
.PARAM vdd={VDD_MIN}
