.PARAM

+_wpmbiasp=2u
+_wp5=2u
+_wp4=2u
+_wp1=2u
+_wp0=2u 
+_wnmbiasp=2u
+_wnmbiasn=2u
+_wn8=2u
+_wn6=2u
+_wn4=2u
+_wn0=2u

+_nfpmbiasp=1 
+_nfp5=1
+_nfp4=1
+_nfp1=1
+_nfp0=1
+_nfnmbiasp=1
+_nfnmbiasn=1
+_nfn8=1 
+_nfn6=1
+_nfn4=1
+_nfn0=1

+_lpmbiasp=340n
+_lp5=340n
+_lp4=340n
+_lp1=340n 
+_lp0=340n
+_lnmbiasp=340n
+_lnmbiasn=340n
+_ln8=340n
+_ln6=340n
+_ln4=340n 
+_ln0=340n

+_nfp7=1
+_wp7=2u
+_lp7=340n