.alter SS_TEMP_MIN
.temp 0
.lib "../../../device_models/libs/sky130A.spice.lib" SS

.alter FFS_TEMP_MIN
.temp 0
.lib "../../../device_models/libs/sky130A.spice.lib" FF

.alter SNFPS_TEMP_MIN
.temp 0
.lib "../../../device_models/libs/sky130A.spice.lib" SNFP

.alter FNSPS_TEMP_MIN
.temp 0
.lib "../../../device_models/libs/sky130A.spice.lib" FNSP



.alter SS_TEMP_MAX
.temp 75
.lib "../../../device_models/libs/sky130A.spice.lib" SS

.alter FFS_TEMP_MAX
.temp 75
.lib "../../../device_models/libs/sky130A.spice.lib" FF

.alter SNFPS_TEMP_MAX
.temp 75
.lib "../../../device_models/libs/sky130A.spice.lib" SNFP

.alter FNSPS_TEMP_MAX
.temp 75
.lib "../../../device_models/libs/sky130A.spice.lib" FNSP


.alter SS
.lib "../../../device_models/libs/sky130A.spice.lib" SS

.alter FF
.lib "../../../device_models/libs/sky130A.spice.lib" FF

.alter SNFP
.lib "../../../device_models/libs/sky130A.spice.lib" SNFP


.alter FNSP
.lib "../../../device_models/libs/sky130A.spice.lib" FNSP
